### ISSUE TITLE
Consider adding Codetta to the list of coding fonts.

### ISSUE THREAD

**Issue by Proeller** [ProgrammingFonts/ProgrammingFonts#15]
[Codetta](https://github.com/Proeller/Codetta) is a font with special ligatures for C#.
It was developed to have a clear and crisp appearance with typically used font sizes of 9Pt and 10Pt but also to scale well on high dpi monitors.
It was taken care that it doesn't use much space and has a better readabillity than the commonly used Consolas in VisualStudio.

**Comment by ifeegoo** [comment]
@Proeller Thank you for you good advice for the font Codetta.I'll add it later.
