### ISSUE TITLE
Proggy Vector

### ISSUE THREAD

**Issue by bluescan** [ProgrammingFonts/ProgrammingFonts#18]
Can be found here if you want to include it: https://github.com/bluescan/proggyfonts

**Comment by ifeegoo** [comment]
@bluescan Thank you for your Proggy Fonts,good programming font,I'll add it later.

**Comment by ifeegoo** [comment]
@bluescan Thank you for your advice, Proggy Fonts are good programming fonts,I'll add it later!

**Comment by ifeegoo** [comment]
@bluescan I have already add Proggy Fonts.

**Comment by bluescan** [comment]
NP. I just thought may want to use the newer Proggy Vector font. It is no longer a pixel font. Up to you.
