### ISSUE TITLE
Any hybrid font?

### ISSUE THREAD

**Issue by swun90** [ProgrammingFonts/ProgrammingFonts#21]
Any Chinese-English hybrid programming font?
I know there's Consolas-with-Yahei, but its line space and word space are larger than the original Consolas. And it goes wrong sometimes, which I guess is because it's not made by professionals.

**Comment by ifeegoo** [comment]
This is a good question. Normally, most of the programming fonts don't have Chinese, because most of the time, we are coding with English, and the difficulty of creating Chinese fonts is more than creating English fonts.So now we can't find a programming font which both supports English & Chinese.

**Comment by alexeyten** [comment]
Check Sarasa Gothic https://github.com/be5invis/Sarasa-Gothic/

**Comment by ifeegoo** [comment]
@alexeyten This is really good, thank you for your notice! @swun90 you can check this.
