### ISSUE TITLE
Various license violations

### ISSUE THREAD

**Issue by braver** [ProgrammingFonts/ProgrammingFonts#22]
Hi, you have a nice collection here! Even some I [haven't seen before](https://programmingfonts.tumblr.com).

There are a bunch here that don't allow you to redistribute the font files via this repo and website though. Including:

- Akkurat
- Consolas
- Andale Mono
- Courier New
- Monaco

Some of these had been [distributed by Microsoft](https://en.wikipedia.org/wiki/Core_fonts_for_the_Web) around 2000, but can only be redistributed in their original form (.exe files) and with inclusion of the EULA. Others, like Consolas and Akkurat are commercial and their licenses certainly don't allow putting them on a website for free. Just so you don't get in trouble here ;)

If you run into anything new, let me know at https://github.com/braver/programmingfonts!

**Comment by ifeegoo** [comment]
Thank you for your friendly reminder! I will check the license later, and some good programming fonts are from your repository, thank you!

**Comment by jakbyte** [comment]
It looks like this still hasn't been resolved.

**Comment by jakbyte** [comment]
It looks like this hasn't been resolved.

**Comment by braver** [comment]
Definitely hasn't.

**Comment by ifeegoo** [comment]
@braver Sorry we are late, I've just removed these fonts.
