### ISSUE TITLE
New release 2.0?

### ISSUE THREAD

**Issue by FuriouslyCurious** [ProgrammingFonts/ProgrammingFonts#26]
Hi team @ifeegoo and @my-gitty,

I noticed that the last release of the repo was in 2015.  Should we spend some time working on the repo and create a 2.0 release?

We can clean up and pull freshest version of all fonts in the repo to work towards the 2.0.

What do you think?

**Comment by ifeegoo** [comment]
@FuriouslyCurious Really good plan, just do it! Thank you for your time spending on this project!

**Comment by ifeegoo** [comment]
@FuriouslyCurious Do you use Telegram? If yes, please add my Telegram: ifeegoo, we can chat online.

**Comment by ifeegoo** [comment]
@FuriouslyCurious I have updated your repository permission, you can do more with it.

**Comment by FuriouslyCurious** [comment]
> @FuriouslyCurious Do you use Telegram? If yes, please add my Telegram: ifeegoo, we can chat online.

Haven't tried Telegram, but let me try it out.  I am also on Slack and Gitter.

**Comment by ifeegoo** [comment]
@FuriouslyCurious OK, just wait for you.

**Comment by my-gitty** [comment]
Ok i also not have telegram

**Comment by my-gitty** [comment]
But I tried it now and added you to chat

**Comment by ifeegoo** [comment]
@my-gitty OK, welcome to the team!
