### ISSUE TITLE
For inclusion of proportional fonts

### ISSUE THREAD

**Issue by matj1** [ProgrammingFonts/ProgrammingFonts#39]
> The programming fonts must have these features.
>
> - **Monospaced**
>
> Monospaced is the most important features for programming fonts, because monospaced fonts are easy for coding which must be easy to check or align or compare.

I disagree with this. Monospacedness is necessary only when alignment is used, which is not always. If I don't have to align, I prefer proportional fonts. Some characters don't fit nicely into a grid for all characters. Even just widening the glyphs of ‘m’, ‘w’, ‘@’ make a monospaced font look better usually.

There are several proportional fonts good for programming:

- [Input Sans](https://input.djr.com/)
- [iA Writer Quattro (Duo)](https://github.com/iaolo/iA-Fonts)
- [Recursive Sans](https://www.recursive.design/)

Other fonts may be good for programming. I like Verdana for programming in languages with long names and not much punctuation, like Java.

**Comment by davidsneighbour** [comment]
That sounds like a personal preference and opinion to me. Fork the repo, add your preferred fonts and use them. Leave the original repo to its specific requirements.

**Comment by matj1** [comment]
Why are the repo's specific requirements exactly these?

It seems that this repository is for sharing among a wide variety of people, so I think it shall offer a wide variety of fonts.

**Comment by ifeegoo** [comment]
@matj1 Hey bro, Monospaced fonts are not 100% necessary for programming, you can also use non-monospaced fonts, it's OK, just do what you like,  as @davidsneighbour said, you can fork or just use the fonts as your version. Good luck to you!

**Comment by matj1** [comment]
@ifeegoo Right. But, if monospaced fonts are not necessary for programming, why is monospacedness the most important feature of fonts for programming according to this repository?

**Comment by diluteoxygen** [comment]
> why is monospacedness the most important feature of fonts for programming according to this repository?

Author's preference.
