### ISSUE TITLE
Add Lilex

### ISSUE THREAD

**Issue by SoraTenshi** [ProgrammingFonts/ProgrammingFonts#44]
[Lilex](https://github.com/mishamyrt/Lilex)

Open source, Monospace, ligature support and there are also NerdFont versions out there (potentially just patched)

I would have created a PR myself, but i am not sure how exactly it should be structured.
Is a submodule fine? Redirect to the repo? Clone and paste the repo?

Maybe this could also be some sort of To-Do to create some small header explaining how to add a font to this repo.

**Comment by ifeegoo** [comment]
@SoraTenshi Thank you for your attention about this project, it's OK for you to create a P/R, you can make similar structure, and then we can make it better, later our team member @diluteoxygen will update how to contribute to this project, @diluteoxygen will do more work about this project.

**Comment by diluteoxygen** [comment]
- Yeah as @ifeegoo mentioned, I'll probably make a guide for PR structure in the near future. But for now, it's good that you suggested these changes, I'll see what I can do. Thanks!

**Comment by diluteoxygen** [comment]
Closing as I've added Lilex, thank you!
