### ISSUE TITLE
Add Maple Mono

### ISSUE THREAD

**Issue by arjpar** [ProgrammingFonts/ProgrammingFonts#45]
[Maple Mono](https://github.com/subframe7536/Maple-font) is an open source monospace programming nerd font with support for ligatures.

**Comment by ifeegoo** [comment]
@arjpar Hey bro, you can just make a pull/request, this is OK and better.

**Comment by arjpar** [comment]
@ifeegoo For the PR: How do I add new fonts to the project? There doesn't seem to be a guide on how to add new fonts.

**Comment by diluteoxygen** [comment]
@arjpar I've added a PR template for new fonts, please check accordingly.
