### ISSUE TITLE
How about we collaborate?

### ISSUE THREAD

**Issue by braver** [ProgrammingFonts/ProgrammingFonts#48]
Hi, I'm the author and maintainer of [programmingfonts.org](https://github.com/braver/programmingfonts). Our projects have lived side by side for close to 10 years now. Mine is roughly a year older, has more fonts and metadata, typically ranks higher in search engines, and attracts more outside contributions. But this one arguably has the better domain name (.com) and more stars in GitHub.

All in all, I think the community would be better served, and our energy spent more purposefully, if we combine our efforts. It seems you're working on a website that [tries to](https://github.com/ProgrammingFonts/ProgrammingFonts/blob/master/todo/ToDo.md#website) do what mine already does. I could save you weeks of development time there. I'm sure there are ways in which you could contribute to that, and to the font listing. And the community would be helped more efficiently by having one repo to go to, to suggest additions and changes. 

So, that was my thinking: let's explore how working together could improve both projects.

**Comment by flygoly** [comment]
@braver Hey bro, it's surprised that you can contact with us, I was aware of your project and website some years ago, and I think that you and your team doing better than us, this is my interest about the programming fonts, so I have done this project some years ago, but we don't have so much time, it's really ok that we can discuss how to work together to make the projects better.

**Comment by diluteoxygen** [comment]
This is a really good initiative, I will agree you guys are doing great! Our small team of contributors would be in debt of your development efforts. I'm still unsure on the ways we could return the favour there, hopefully we can find a common path that overall impacts the community positively. Me and @ifeegoo have already discussed on few possibilities of our combined efforts, we are more than willing to discuss the same with you guys. We're open to hearing all the collaborative discussions. Thank you @braver

**Comment by braver** [comment]
Guys, thanks for responding so quickly and positively.  ❤️ 

I don't spend a lot of time on the project overall, although recently I put in some more work for improvements, all I usually really do is keep the listing up to date. 

Yesterday I picked up some fonts that were added here that I was missing, most notably [Maple](http://localhost/~koenlageveen/programmingfonts/#maple). I would like for us to somehow at the very least unify the listing, find some way to keep each other up to date, and for the community to have one place to go to and report new fonts they found or created. Half of what I add comes in via [tumblr](https://programmingfonts.tumblr.com) by the way.

The heart of my project is the [fonts.json](https://github.com/braver/programmingfonts/blob/gh-pages/fonts.json) file (and its [schema](https://github.com/braver/programmingfonts/blob/gh-pages/fonts-schema.json)). My effort is currently mostly aimed at adding descriptions, license, and variations data on all the fonts. I'm at ~75% but it's a bit of an ongoing effort: there is always more detail that can be added and fonts change over time. 

So one way to approach this could be that we make that file the single "source of truth": you can contribute to that for any additions you need (e.g. additional properties), and you can use the file to generate whatever output you have in mind (e.g. a static listing of all fonts in an HTML or markdown page somewhere). I wouldn't mind giving you access to my repo if that makes things easier. Or we could talk about maybe putting both projects under the Programmingfonts org umbrella eventually.

I guess the question would be what your goals for this project are, how they're aligned with mine and can benefit from what's already there, and then also how your work could enrich my project. Maybe we're better off having one big project, but I can also see how this is just a hobby and we like each having our repo's to do whatever we want to without a lot of coordination. And anyway, there is not stopping us from keeping each other up to date on new additions etc. 

... so maybe let me start over by stating my goals :) It's (in random order):

A. a website I can play with to try new ideas, technologies and design inspiration
B. a database of fonts where users can explore and discover fonts they can go and use (not necessarily for free)
C. a way for me to keep up to date on new fonts but also developments in (web-) typography like variable fonts, opentype support, etc.
D. a platform to increase the visibility of the creators of those fonts and drive traffic to their website (ie. it's explicitly not a download portal, als for several more practical reasons)

**Comment by diluteoxygen** [comment]
First and foremost, It is truly inspiring to see the potential for our projects to complement each other and create a stronger platform for the PF community❤️ I'm excited about the possibilities that lie ahead. In addition to unifying the font listings through the fonts.json file, We believe we could explore some unique ideas that could enhance the UX. Building upon some of your goals, here's a few that I was thinking about:

1. **Font Pairing & Recommendations⭐:** To cater to designers' needs, we could develop a feature that suggests font pairings and recommends complementary fonts based on user preferences.
2. **Upvote🔼 / Downvote🔽  Fonts:** Let the community upvote their favorite fonts, ensuring that the most popular and high-quality fonts gain traction.  ⭐ 

Regarding the integration of our projects, We believe that maintaining both our unique identities and creative freedom is essential. However, I agree that a single "source of truth" would be powerful, to ensure consistency & ease.

Before finalizing any decisions, We would appreciate some time to discuss these ideas further and consider the best course of action. Could we perhaps communicate via Discord or something if that's gonna help with better communication? Thank you for your understanding, and We look forward to our upcoming conversation.

**Comment by braver** [comment]
Love the idea of up/down votes, I’m always curious to see what’s popular. This could be accomplished through an analytics service like Plausible, but I’m hesitant to take on additional cost (or using a profiling/tracking based solution even though that might be “free”). I’m just using GitHub pages for hosting, not sure how I would otherwise store data like that.

> We believe that maintaining both our unique identities and creative freedom is essential.

I agree completely. Let’s help each other without getting in each other’s way.

> Could we perhaps communicate via Discord

I’m already in a couple of Slack’s, that could also work. But I also like the idea of opening up something public where people can join and discuss, notify us of new fonts, etc. Maybe Discord is better for that. I’m in some Discord channels around Sublime Text, I just don’t log in there very often and am not as familiar with how it actually works. Maybe you can already find me on Discord by my GitHub handle (or `@braver__`)?

**Comment by braver** [comment]
Huh, I think I just created a Discord server where we can chat: https://discord.gg/wv2ZXjE7 .. does this thing work? 🤔😅

**Comment by flygoly** [comment]
@braver yeah, it's OK, we can chat on Discord, but there is something wrong the the invite link, I can't enter;

**Comment by braver** [comment]
~~Let's try that again then: https://discord.gg/wv2ZXjE7 (`https://discord.gg/wv2ZXjE7`)~~

**Comment by braver** [comment]
I changed the link: https://discord.gg/feUp7rVs4Q
