### ISSUE TITLE
Please, whats the color scheme on screenshots?

### ISSUE THREAD

**Issue by richellyitalo** [ProgrammingFonts/ProgrammingFonts#9]
Please, whats the color scheme on screenshots?

**Comment by ifeegoo** [comment]
@richellyitalo I have forgot the color scheme of the screenshots,because I reinstalled my IDE long time before.But I strongly recommend you 2 websites: http://color-themes.com/ http://www.eclipsecolorthemes.org/

**Comment by richellyitalo** [comment]
Thanks @ifeegoo .
Merry Christmas!

**Comment by ifeegoo** [comment]
@richellyitalo The same to you! 🎄🎄🎄
